management:
  endpoints:
    web:
      exposure:
        include: health, beans

  endpoint:
    health:
      enabled: false

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/flights
    username: root
    password: dbpw
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    open-in-view: false

  servlet:
    multipart:
      max-file-size: 2MB


#  messages:
#    basename: messages/messages
#    use-code-as-default-message: true
#    fallback-to-system-locale: false  # Añade esta línea

application:
  store:
    base-path: C:\Users\sergi\IntelliJProjects\flight-app-working-files

#logging:
#  level:
#    org.hibernate.SQL: debug
#    org.hibernate.orm.jdbc.bind: trace