server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: health, beans
  endpoint:
    health:
      enabled: false

spring:
  application:
    name: file-store-api

application:
  store:
    base-path: C:\Users\sergi\IntelliJProjects\flight-app-working-files

logging:
  file:
    path: C:\Users\sergi\IntelliJProjects
