spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/airport_batch
    username: root
    password: dbpw
  batch:
    jdbc:
      initialize-schema: ALWAYS

application:
  batch:
    base-path: C:\Users\sergi\IntelliJProjects\flight-app-batch-working-files